swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert("Mensagem Exibida no Alert")//
info:
  version: "1.0.0"
  title: XSS img test
  description: |
    <img src="https://www.viajandopelahistoriadoriodejaneiro.com/post/palha%C3%A7o-carequinha" onload="alert('Mensagem no Alert')" />
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
